airflow:
    connections:
        - conn_id: my_spark_conn
          conn_type: spark
          conn_host: spark://spark-master
          conn_port: 7077
          conn_extra:
              deploy-mode: client
              spark_binary: spark-submit
        - conn_id: elasticsearch_default
          conn_type: elasticsearch
          conn_host: es01
          conn_port: 9200
          conn_schema: http
        - conn_id: kibana_default
          conn_type: http
          conn_host: kibana
          conn_port: 5601
          conn_schema: http
    pools: []
    variables:
        - key: ELASTICSEARCH_HOST
          value: "http://es01:9200"
        - key: KIBANA_HOST
          value: "http://kibana:5601"