airflow:
    connections:
        - conn_id: my_spark_conn
          conn_type: spark
          conn_host: spark://spark-master
          conn_port: 7077
          conn_extra:
              deploy-mode: client
              spark_binary: spark-submit
        - conn_id: elasticsearch_default
          conn_type: elasticsearch
          conn_host: es01
          conn_port: 9200
          conn_schema: https
          conn_login: elastic
          conn_password: elastic
          conn_extra:
              verify_ssl: false
              verify_certs: false
        - conn_id: kibana_default
    pools: []
    variables:
        - key: ELASTICSEARCH_HOST
          value: "https://es01:9200"
        - key: ELASTICSEARCH_USERNAME
          value: "elastic"
        - key: ELASTICSEARCH_PASSWORD
          value: "elastic"
        - key: KIBANA_HOST
          value: "https://kibana:5601"