services:
  # Single Elasticsearch node for development (no security)
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=false
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.ml.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx1g"
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - ./include:/usr/share/elasticsearch/data/nutriweather
    ports:
      - "9200:9200"
    mem_limit: 2g
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - airflow

  # Kibana service (no security)
  kibana:
    depends_on:
      es01:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - xpack.security.enabled=false
      - xpack.encryptedSavedObjects.encryptionKey=fhjskloppd678ehkdfdlliverpoolfcr
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - "5601:5601"
    mem_limit: 1g
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - airflow

  # Spark Master
  spark-master:
    image: bitnami/spark:3.5.6
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_MASTER_WEBUI_PORT=8082
    ports:
      - '8082:8082'
      - '7077:7077'
    volumes:
      - spark-data:/bitnami
      - ./include:/usr/local/airflow/include
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    networks:
      - airflow

  # Spark Worker
  spark-worker:
    image: bitnami/spark:3.5.6
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./include:/usr/local/airflow/include
      - spark-data:/bitnami
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    depends_on:
      - spark-master
    networks:
      - airflow

  # HDFS NameNode
  namenode:
    image: apache/hadoop:3.3.5
    container_name: namenode
    hostname: namenode
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_HEAPSIZE=1024
      - HADOOP_NAMENODE_OPTS="-Xmx1g"
    volumes:
      - namenode-data:/opt/hadoop/data/nameNode
      - ./hdfs_config:/opt/hadoop/etc/hadoop
      - ./scripts/start-hdfs.sh:/start-hdfs.sh
      - ./include:/usr/local/airflow/include
    ports:
      - "9870:9870"  # HDFS Web UI
      - "8020:8020"  # HDFS API
    command: ["/bin/bash", "/start-hdfs.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9870"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    mem_limit: 2g
    restart: unless-stopped
    networks:
      - airflow

  # HDFS DataNode 1
  datanode1:
    image: apache/hadoop:3.3.5
    container_name: datanode1
    hostname: datanode1
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_HEAPSIZE=512
    volumes:
      - datanode1-data:/opt/hadoop/data/dataNode
      - ./hdfs_config:/opt/hadoop/etc/hadoop
      - ./scripts/init-datanode.sh:/init-datanode.sh
      - ./include:/usr/local/airflow/include
    depends_on:
      namenode:
        condition: service_healthy
    command: ["/bin/bash", "/init-datanode.sh"]
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - airflow

  # HDFS DataNode 2
  datanode2:
    image: apache/hadoop:3.3.5
    container_name: datanode2
    hostname: datanode2
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_HEAPSIZE=512
    volumes:
      - datanode2-data:/opt/hadoop/data/dataNode
      - ./hdfs_config:/opt/hadoop/etc/hadoop
      - ./scripts/init-datanode.sh:/init-datanode.sh
      - ./include:/usr/local/airflow/include
    depends_on:
      namenode:
        condition: service_healthy
    command: ["/bin/bash", "/init-datanode.sh"]
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - airflow

volumes:
  # Elastic Stack volumes
  esdata01:
    driver: local
  kibanadata:
    driver: local
  # Spark volume
  spark-data:
  # HDFS volumes
  namenode-data:
    driver: local
  datanode1-data:
    driver: local
  datanode2-data:
    driver: local

networks:
  airflow:
    # external: true